// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/xmvideo/feedback/update.ts";
import * as $5 from "./routes/docs/[...slug].tsx";
import * as $6 from "./routes/fresh.tsx";
import * as $7 from "./routes/gfm.css.ts";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/raw.ts";
import * as $10 from "./routes/showcase.tsx";
import * as $11 from "./routes/update.tsx";
import * as $12 from "./routes/xmvideo/update/[platform]/[version].tsx";
import * as $$0 from "./islands/CopyArea.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/FreshGettingStarted.tsx";
import * as $$3 from "./islands/LemonDrop.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/xmvideo/feedback/update.ts": $4,
    "./routes/docs/[...slug].tsx": $5,
    "./routes/fresh.tsx": $6,
    "./routes/gfm.css.ts": $7,
    "./routes/index.tsx": $8,
    "./routes/raw.ts": $9,
    "./routes/showcase.tsx": $10,
    "./routes/update.tsx": $11,
    "./routes/xmvideo/update/[platform]/[version].tsx": $12,
  },
  islands: {
    "./islands/CopyArea.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/FreshGettingStarted.tsx": $$2,
    "./islands/LemonDrop.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
