// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/docs/[...slug].tsx";
import * as $4 from "./routes/fresh.tsx";
import * as $5 from "./routes/gfm.css.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/raw.ts";
import * as $8 from "./routes/showcase.tsx";
import * as $9 from "./routes/update.tsx";
import * as $10 from "./routes/xmvideo/_middleware.ts";
import * as $11 from "./routes/xmvideo/update/[platform]/[version].tsx";
import * as $$0 from "./islands/CopyArea.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/LemonDrop.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/docs/[...slug].tsx": $3,
    "./routes/fresh.tsx": $4,
    "./routes/gfm.css.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/raw.ts": $7,
    "./routes/showcase.tsx": $8,
    "./routes/update.tsx": $9,
    "./routes/xmvideo/_middleware.ts": $10,
    "./routes/xmvideo/update/[platform]/[version].tsx": $11,
  },
  islands: {
    "./islands/CopyArea.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/LemonDrop.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
